FROM amsterdam/python
MAINTAINER datapunt@amsterdam.nl

ENV PYTHONUNBUFFERED 1

EXPOSE 8000

RUN mkdir -p /static \
	&& mkdir /data \
	&& chown datapunt /data \
	&& chown datapunt /static

WORKDIR /app
COPY ./tests/requirements.test.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

USER datapunt
COPY ./tests/web/app/ /app/
COPY ./tests/web/deploy/ /deploy/
