name: CI
on:
  pull_request: ~
  schedule:
    # 12:30 UTC is at 8:30 or 9:30 EST depending on DST
    - cron: '30 12 * * *'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build container image
        run: docker-compose build

      - name: Run tests
        run: make pytest

      - name: Run isort
        run: make isort

      - name: Run flake8
        run: make flake8

      - name: Run mypy
        run: make mypy
